### ISSUE TITLE
Create, decide and describe a way to publish documentation

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/GRASS_FUTURES#1]
Currently, a gh-pages branch exists which causes public pages to appear at http://ncsu-landscape-dynamics.github.io/GRASS_FUTURES. The content is generated by few scripts. The last release documentation is atogether with code in GRASS GIS addons and the documentation for all addons goes online. If this will work well with multiple modules (e.g. r.futures.pga, r.futures.patches), the gh-pages would be just for internal/developer use and devs can look at them, although in worse form, in the repository, different versions online can cause confusion or other unwanted effects especially if the documented code was not yet published.

I see the following options:
- remove gh-pages branch
  - common users have the docs which comes with GRASS modules
  - devs have to deal with not having online doc
- update gh-pages branch carefully to publish only what should be publish
  - a "release branch" can be used to ensure "careful" (this requires addition work, see also next option)
- say that everything in master can be already public
  - supposing that gh-pages branch will be anyway updated only from master (although other solutions might have some advantages)
  - in the case of public master, it would make sense to have public repository with this master branch and have "topic" branches connected to different repositories (this requires addition work and it this is out of scope of this issue)
- create repository which will serve mainly for the pages
  - this can be combined with the two previous options but has the same disadvantage of additional work (moving more things around when we are already publishing releases trough GRASS repository)
  - repository might be created anyway to provide public way to report issues and perhaps also a wiki (also out of scope of this issue)

**Comment by petrasovaa** [comment]
Deleted gh-pages for now.
