### ISSUE TITLE
Add GitHub Actions to run tests

### ISSUE THREAD

**Issue by wenzeslaus** [ncsu-landscape-dynamics/GRASS_FUTURES#6]
For reproducibility, this should be both on change and periodically as a cron job.

**Comment by wenzeslaus** [comment]
#7 adds the CI on pull and PR, but the cron job is still missing.

**Comment by petrasovaa** [comment]
Cron job in #8, not working right now.

**Comment by wenzeslaus** [comment]
After merging #8, cron jobs are on master and are running now.
